begin;
do $$
declare uid uuid; cid uuid; secret text:=encode(extensions.gen_random_bytes(32),'hex'); code text:=encode(extensions.gen_random_bytes(32),'hex'); access text:='aq_oauth_'||encode(extensions.gen_random_bytes(32),'hex'); refresh text:=encode(extensions.gen_random_bytes(32),'hex'); access2 text:='aq_oauth_'||encode(extensions.gen_random_bytes(32),'hex'); refresh2 text:=encode(extensions.gen_random_bytes(32),'hex'); sid uuid; resource text:='https://alyquestv3.vercel.app/api/mcp'; callback text:='https://chatgpt.com/connector_platform_oauth_redirect'; challenge text:=repeat('a',43); rejected boolean;
begin
 select id into uid from auth.users order by created_at limit 1;
 if uid is null then raise exception 'No existing user available for rollback-only test'; end if;
 perform set_config('request.jwt.claim.sub',uid::text,true);
 cid:=public.aq_mcp_register_client('Rollback MCP test',array[callback],secret);
 perform public.aq_mcp_authorize(cid,callback,challenge,code);
 rejected:=false;
 begin perform public.aq_mcp_exchange('authorization_code',cid,secret,code,callback,repeat('b',43),access,refresh,resource); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'PKCE mismatch accepted'; end if;
 rejected:=false;
 begin perform public.aq_mcp_exchange('authorization_code',cid,'wrong',code,callback,challenge,access,refresh,resource); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Invalid client secret accepted'; end if;
 rejected:=false;
 begin perform public.aq_mcp_exchange('authorization_code',cid,secret,code,callback,challenge,access,refresh,'https://wrong.example'); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Wrong resource accepted'; end if;
 perform public.aq_mcp_exchange('authorization_code',cid,secret,code,callback,challenge,access,refresh,resource);
 if public.aq_gpt_token_user(access)<>uid then raise exception 'Wrong token owner'; end if;
 rejected:=false;
 begin perform public.aq_mcp_exchange('authorization_code',cid,secret,code,callback,challenge,access,refresh,resource); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Code replay accepted'; end if;
 perform public.aq_mcp_exchange('refresh_token',cid,secret,refresh,'','',access2,refresh2,resource);
 rejected:=false;
 begin perform public.aq_gpt_token_user(access); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Old access token remained active'; end if;
 rejected:=false;
 begin perform public.aq_mcp_exchange('refresh_token',cid,secret,refresh,'','',access,refresh,resource); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Refresh replay accepted'; end if;
 update public.aq_integration_tokens set expires_at=now()-interval '1 second' where token_hash=encode(extensions.digest(access2,'sha256'),'hex');
 rejected:=false;
 begin perform public.aq_gpt_token_user(access2); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Expired token accepted'; end if;
 update public.aq_integration_tokens set expires_at=now()+interval '1 hour' where token_hash=encode(extensions.digest(access2,'sha256'),'hex');
 select id into sid from public.aq_mcp_oauth_sessions where client_id=cid;
 perform public.aq_mcp_revoke(sid);
 rejected:=false;
 begin perform public.aq_gpt_token_user(access2); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Revoked access token accepted'; end if;
 rejected:=false;
 begin perform public.aq_mcp_exchange('refresh_token',cid,secret,refresh2,'','',access,refresh,resource); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'Revoked refresh token accepted'; end if;
 if has_table_privilege('anon','public.aq_mcp_oauth_codes','select') or has_table_privilege('authenticated','public.aq_mcp_oauth_sessions','select') or has_function_privilege('anon','public.aq_mcp_authorize(uuid,text,text,text)','execute') then raise exception 'Unexpected public privileges'; end if;
end $$;
rollback;
select 'PKCE, client authentication, resource binding, code replay, refresh rotation, expiration, revocation and database permissions passed; all test writes rolled back.' as verification;
