export const instant = false;
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ActionForm } from "@/components/action-form";
import { saveNightReview } from "@/app/system-actions";
import { saoDate, soft } from "@/lib/life-dashboard";

type Review={wins:string|null;blockers:string|null;tomorrow:string|null;mood:number|null};
export default async function Page(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login');const day=saoDate();const review=await soft<Review|null>(supabase.from('aq_night_reviews').select('*').eq('user_id',user.id).eq('review_day',day).maybeSingle(),null);return <main className="min-h-screen px-4 pb-28 pt-6"><div className="mx-auto max-w-md"><h1 className="text-2xl font-black">Revisão noturna</h1><p className="mt-1 text-sm text-slate-400">Feche o dia com clareza e prepare amanhã.</p><ActionForm action={saveNightReview} className="mt-5 rounded-3xl border border-slate-800 bg-slate-900 p-4"><input type="hidden" name="day" value={day}/><label className="block text-sm font-bold">Vitórias de hoje<textarea name="wins" defaultValue={review?.wins??''} className="mt-2 h-24 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="mt-4 block text-sm font-bold">Bloqueios / ajustes<textarea name="blockers" defaultValue={review?.blockers??''} className="mt-2 h-24 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="mt-4 block text-sm font-bold">Primeiro passo de amanhã<textarea name="tomorrow" defaultValue={review?.tomorrow??''} className="mt-2 h-24 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><label className="mt-4 block text-sm font-bold">Humor<input name="mood" type="range" min="1" max="5" defaultValue={review?.mood??3} className="mt-2 w-full"/></label><button className="mt-4 w-full rounded-xl bg-emerald-600 p-3 font-bold">Salvar revisão</button></ActionForm></div></main>}
