export const instant = false;
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ActionForm } from "@/components/action-form";
import { saveDailyPlan } from "@/app/system-actions";
import { saoDate, soft } from "@/lib/life-dashboard";

type Task={id:string;title:string;category:string|null;due_date:string|null;estimated_hours:number|string|null}; type Plan={intention:string|null;workout_intention:string|null;focus_minutes:number|null;top_task_ids:string[]|null};
export default async function Page(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login');const day=saoDate();const [tasks,plan]=await Promise.all([soft<Task[]>(supabase.from('tasks').select('id,title,category,due_date,estimated_hours').eq('user_id',user.id).eq('status','pending').order('due_date',{ascending:true,nullsFirst:false}).limit(20),[]),soft<Plan|null>(supabase.from('aq_daily_plans').select('*').eq('user_id',user.id).eq('plan_day',day).maybeSingle(),null)]);const selected=new Set(plan?.top_task_ids??[]);return <main className="min-h-screen px-4 pb-28 pt-6"><div className="mx-auto max-w-md"><h1 className="text-2xl font-black">Organizar meu dia</h1><p className="mt-1 text-sm text-slate-400">Escolha as missões mais importantes, anote sua intenção e reserve tempo para treino e foco. Este plano é uma referência para hoje; ele não muda os prazos das tarefas.</p><ActionForm action={saveDailyPlan} className="mt-5 rounded-3xl border border-slate-800 bg-slate-900 p-4"><input type="hidden" name="day" value={day}/><label className="block text-sm font-bold">O que quero priorizar hoje<textarea name="intention" defaultValue={plan?.intention??''} className="mt-2 h-24 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Ex.: hoje vou resolver as pendências críticas sem atropelar minha energia."/></label><div className="mt-4"><p className="text-sm font-bold">Missões prioritárias</p><div className="mt-2 space-y-2">{tasks.map(t=><label key={t.id} className="flex gap-3 rounded-2xl border border-slate-800 bg-slate-950 p-3 text-sm"><input type="checkbox" name="top_task_ids" value={t.id} defaultChecked={selected.has(t.id)}/><span><b>{t.title}</b><br/><span className="text-xs text-slate-400">{t.category??'Sem categoria'}{t.due_date?` · prazo ${t.due_date}`:''}</span></span></label>)}</div></div><label className="mt-4 block text-sm font-bold">Treino de hoje<input name="workout_intention" defaultValue={plan?.workout_intention??''} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Ex.: esteira 3k + abdominal"/></label><label className="mt-4 block text-sm font-bold">Minutos de foco<input name="focus_minutes" type="number" min="0" max="600" defaultValue={plan?.focus_minutes??25} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"/></label><button className="mt-4 w-full rounded-xl bg-violet-600 p-3 font-bold">Salvar meu plano de hoje</button></ActionForm></div></main>}
