"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
async function requireUser(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Usuário não autenticado");return {supabase,user};}
export async function createTask(formData:FormData){const {supabase,user}=await requireUser();const title=String(formData.get('title')??'').trim();const category=String(formData.get('category')??'Pessoal');const priority=String(formData.get('priority')??'medium');const estimatedHours=Number(formData.get('estimated_hours')??1);const dueDateRaw=String(formData.get('due_date')??'');const bossIdRaw=String(formData.get('boss_id')??'');if(!title)throw new Error('Informe o nome da tarefa.');const {error}=await supabase.from('tasks').insert({user_id:user.id,title,category,priority,estimated_hours:Number.isFinite(estimatedHours)&&estimatedHours>0?estimatedHours:1,due_date:dueDateRaw||null,boss_id:bossIdRaw||null,status:'pending'});if(error)throw new Error(error.message);revalidatePath('/');revalidatePath('/tasks');revalidatePath('/focus');}
export async function completeTask(taskId:string){const {supabase}=await requireUser();const {error}=await supabase.rpc('complete_task',{p_task_id:taskId});if(error)throw new Error(error.message);['/','/tasks','/workouts','/focus','/bosses','/shop','/achievements'].forEach(path => revalidatePath(path));}
export async function completePomodoroPhase(sessionId:string|null,taskId:string|null,phase:'focus'|'break',focusMinutes:number,breakMinutes:number){const {supabase}=await requireUser();const {data,error}=await supabase.rpc('complete_pomodoro_phase',{p_session_id:sessionId,p_task_id:taskId,p_phase:phase,p_focus_minutes:focusMinutes,p_break_minutes:breakMinutes});if(error)throw new Error(error.message);revalidatePath('/');revalidatePath('/focus');revalidatePath('/shop');revalidatePath('/achievements');return data as string;}
export async function purchaseItem(itemId:string){const {supabase}=await requireUser();const {error}=await supabase.rpc('purchase_item',{p_item_id:itemId});if(error)throw new Error(error.message);revalidatePath('/');revalidatePath('/shop');}
export async function equipItem(itemId:string){const {supabase}=await requireUser();const {error}=await supabase.rpc('equip_item',{p_item_id:itemId});if(error)throw new Error(error.message);revalidatePath('/');revalidatePath('/shop');revalidatePath('/bosses');}
export async function syncLoginStreak(){const {supabase}=await requireUser();const {error}=await supabase.rpc('sync_login_streak');if(error)throw new Error(error.message);revalidatePath('/');revalidatePath('/achievements');}
