import { displayName } from "@/lib/user-preferences";
import Link from 'next/link';
import {Suspense} from 'react';
import {createClient} from '@/lib/supabase/server';
import {checked} from '@/lib/query';
import {loadPlanning} from '@/lib/planning-server';
import {today} from '@/lib/planning';
import {taskDayGroup} from '@/lib/task-dates';
import {PlayerCard} from '@/components/player-card';
import {BossCard} from '@/components/boss-card';
import {MissionCard} from '@/components/mission-card';
import {LoginSync} from '@/components/login-sync';
import {RoutineSync} from '@/components/routine-sync';
async function Dashboard(){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return <main className="min-h-screen p-6"><div className="mx-auto max-w-md"><h1 className="text-2xl font-black">AlyQuest</h1><p className="mt-3 text-slate-400">Faça login para continuar sua jornada.</p><Link href="/auth/login" className="mt-5 block rounded-xl bg-violet-600 p-3 text-center font-bold">Entrar</Link></div></main>;
 const date=today();
 await s.rpc('aq_generate_daily_missions',{p_day:date});
 const [tr,br,xr,cr,pr,planResult,questResult,planning]=await Promise.all([s.from('tasks').select('*').eq('user_id',user.id).eq('status','pending').order('due_date',{ascending:true,nullsFirst:false}),s.from('bosses').select('*').eq('user_id',user.id).is('defeated_at',null).order('created_at'),s.from('xp_transactions').select('amount').eq('user_id',user.id),s.from('coin_transactions').select('amount').eq('user_id',user.id),s.from('profiles').select('current_streak').eq('user_id',user.id).maybeSingle(),s.from('aq_daily_plans').select('intention,top_task_ids,workout_intention,focus_minutes').eq('user_id',user.id).eq('plan_day',date).maybeSingle(),s.from('aq_daily_missions').select('id,title,progress_count,target_count,completed_at').eq('user_id',user.id).eq('mission_day',date).order('created_at').limit(3),loadPlanning(s,user.id)]);[tr,br,xr,cr,pr].forEach(checked);
 const tasks=tr.data??[],bosses=br.data??[],xp=(xr.data??[]).reduce((n,r)=>n+Number(r.amount),0),coins=(cr.data??[]).reduce((n,r)=>n+Number(r.amount),0);
 const card=(t:typeof tasks[number])=><MissionCard key={t.id} task={t} planning={planning} bosses={bosses}/>;
 const workouts=tasks.filter(t=>t.due_date===date&&planning.plans.some(p=>p.task_id===t.id&&p.kind==='workout'));
 const daily=tasks.filter(t=>taskDayGroup(t,date)==='today'&&!workouts.some(w=>w.id===t.id));
 const plan=planResult.data,quests=questResult.data??[];
 const nextTask=(plan?.top_task_ids??[]).map((id:string)=>tasks.find(t=>t.id===id)).find(Boolean)??daily[0]??tasks.find(t=>taskDayGroup(t,date)==='overdue')??null;
 return <main className="min-h-screen px-4 pb-28 pt-6"><LoginSync/><RoutineSync/><div className="mx-auto w-full min-w-0 max-w-md"><header className="mb-4 flex min-w-0 items-center justify-between gap-2"><div className="min-w-0"><p className="text-xs text-violet-300">⚔️ AlyQuest</p><h1 className="mt-1 text-2xl font-black">Hoje</h1><p className="text-xs text-slate-400">{new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</p></div><div className="flex shrink-0 gap-2"><Link href="/notifications" aria-label="Lembretes" className="grid min-h-11 min-w-11 place-items-center rounded-xl border border-slate-700 text-sm font-bold">🔔</Link><Link href="/focus" className="grid min-h-11 place-items-center rounded-xl bg-violet-600 px-3 text-sm font-bold">🍅 Foco</Link></div></header>
 <nav className="mb-4 grid min-w-0 grid-cols-3 gap-2 text-center text-xs font-bold"><Link href="/daily" className="grid min-h-11 min-w-0 place-items-center rounded-xl border border-violet-700 bg-slate-900 p-2">✨ Diárias</Link><Link href="/weekly" className="grid min-h-11 min-w-0 place-items-center rounded-xl border border-violet-700 bg-slate-900 p-2">📊 Semana</Link><Link href="/inbox" className="grid min-h-11 min-w-0 place-items-center rounded-xl border border-violet-700 bg-slate-900 p-2">📥 Capturar</Link></nav>
 <PlayerCard name={displayName(user.user_metadata)} xp={xp} coins={coins} streak={pr.data?.current_streak??0} pendingTasks={tasks.length}/>
 <section className="mt-4 rounded-3xl border border-violet-700/70 bg-gradient-to-br from-violet-950 to-slate-900 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-200">Seu próximo passo</p><h2 className="mt-2 text-lg font-black">{nextTask?.title??(workouts.length?'Seu treino está pronto':'Escolha uma prioridade para hoje')}</h2><p className="mt-1 text-sm text-slate-300">{plan?.intention||'Um passo de cada vez. Você pode definir suas prioridades e começar quando quiser.'}</p></div><span aria-hidden className="text-2xl">🎯</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Link href={nextTask?'/tasks':workouts.length?'/workouts':'/planning'} className="min-h-11 rounded-xl bg-violet-600 px-3 py-3 text-center text-sm font-bold">{nextTask?'Abrir missão':workouts.length?'Abrir treino':'Planejar o dia'}</Link><Link href="/focus" className="min-h-11 rounded-xl border border-violet-500 px-3 py-3 text-center text-sm font-bold">{plan?.focus_minutes?`Foco · ${plan.focus_minutes} min`:'Iniciar foco'}</Link></div>{plan?.workout_intention&&<p className="mt-3 text-xs text-violet-200">🏋️ Treino planejado: {plan.workout_intention}</p>}</section>
 <section className="mt-4 rounded-2xl border border-slate-700 bg-slate-900 p-4"><div className="flex items-center justify-between gap-2"><h2 className="font-bold">✨ Três desafios do dia</h2><Link href="/daily" className="text-sm text-violet-300">Ver diárias →</Link></div><div className="mt-3 space-y-2">{quests.map(q=><div key={q.id} className="flex items-center justify-between gap-3 text-sm"><span className={q.completed_at?'text-emerald-300':'text-slate-200'}>{q.completed_at?'✓ ':''}{q.title}</span><span className="shrink-0 text-xs text-slate-400">{q.progress_count}/{q.target_count}</span></div>)}{!quests.length&&<p className="text-sm text-slate-400">Abra as missões diárias para ver os desafios de hoje.</p>}</div></section>
 <div className="mb-3 mt-6 flex items-center justify-between"><h2 className="font-bold">Missões de hoje ({daily.length})</h2><Link href="/tasks" className="text-sm text-violet-300">Todas / + Nova</Link></div><div className="space-y-2">{daily.map(card)}{!daily.length&&<p className="text-sm text-slate-400">Nenhuma missão com prazo para hoje. Você pode escolher uma sem data abaixo.</p>}</div>
 <div className="mb-3 mt-6 flex items-center justify-between"><h2 className="font-bold">Treino de hoje</h2><Link href="/workouts" className="text-sm text-violet-300">Planejar semana</Link></div><div className="space-y-2">{workouts.map(card)}{!workouts.length&&<Link href="/workouts" className="block rounded-xl border border-slate-700 p-3 text-sm text-slate-300">Escolher módulos ou deixar para decidir depois →</Link>}</div>
 {([['overdue','Atrasadas'],['unscheduled','Sem data'],['future','Futuras']] as const).map(([group,label])=>{const items=tasks.filter(t=>taskDayGroup(t,date)===group);return <details key={group} className="mt-5 rounded-2xl border border-slate-800 p-3"><summary className="cursor-pointer font-semibold">{label} ({items.length})</summary><div className="mt-3 space-y-2">{items.map(card)}{!items.length&&<p className="text-sm text-slate-400">Nenhuma missão neste grupo.</p>}</div></details>;})}
 <div className="mb-3 mt-6 flex justify-between"><h2 className="font-bold">Chefe atual</h2><Link href="/bosses" className="text-sm text-violet-300">Ver metas</Link></div><BossCard boss={bosses[0]??null}/>
 </div></main>;
}
export default function Home(){return <Suspense fallback={<main className="p-6">Carregando seu dia…</main>}><Dashboard/></Suspense>;}
