export const instant = false;
import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { ActionForm } from "@/components/action-form";
import { saveFinanceBudget } from "@/app/system-actions";
import { currentMonth, financeCategories, firstDay, lastDay, money, progressPct, soft, sum } from "@/lib/life-dashboard";

type Budget={category:string;amount:number|string}; type Tx={category:string|null;amount:number|string;kind:string};
export default async function Page(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login');const month=currentMonth();const [budgets,txs]=await Promise.all([soft<Budget[]>(supabase.from('aq_finance_budgets').select('category,amount').eq('user_id',user.id).eq('budget_month',month),[]),soft<Tx[]>(supabase.from('aq_finance_transactions').select('category,amount,kind').eq('user_id',user.id).gte('occurred_on',firstDay(month)).lte('occurred_on',lastDay(month)),[])]);return <main className="min-h-screen px-4 pb-28 pt-6"><div className="mx-auto max-w-md"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black">Orçamento mensal</h1><p className="mt-1 text-sm text-slate-400">Teto por categoria e quanto ainda pode gastar.</p></div><Link href="/finance" className="text-sm text-violet-300">Finanças</Link></div><ActionForm action={saveFinanceBudget} className="mt-5 rounded-3xl border border-slate-800 bg-slate-900 p-4"><input type="hidden" name="month" value={month}/><div className="grid grid-cols-2 gap-3"><select name="category" className="rounded-xl border border-slate-700 bg-slate-950 p-3">{financeCategories.map(c=><option key={c}>{c}</option>)}</select><input name="amount" inputMode="decimal" required placeholder="Teto" className="rounded-xl border border-slate-700 bg-slate-950 p-3"/></div><button className="mt-3 w-full rounded-xl bg-violet-600 p-3 font-bold">Salvar teto</button></ActionForm><section className="mt-5 space-y-3">{financeCategories.map(cat=>{const budget=Number(budgets.find(b=>b.category===cat)?.amount??0);const spent=sum(txs.filter(t=>t.kind==='expense'&&(t.category??'Outros')===cat),t=>t.amount);const remaining=budget-spent;return <article key={cat} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{cat}</h2><p className="text-xs text-slate-400">Gasto {money.format(spent)} de {budget?money.format(budget):'sem teto'}</p></div><p className={remaining>=0?'font-bold text-emerald-300':'font-bold text-rose-300'}>{budget?money.format(remaining):'—'}</p></div><div className="mt-3 h-3 rounded-full bg-slate-950"><div className={`h-3 rounded-full ${budget&&spent>budget?'bg-rose-500':'bg-emerald-500'}`} style={{width:budget?progressPct(spent,budget):'4%'}}/></div></article>})}</section></div></main>}
