export const instant = false;
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ActionForm } from "@/components/action-form";
import { saveQuickInbox, updateQuickInboxForm } from "@/app/system-actions";
import { soft } from "@/lib/life-dashboard";

type Entry={id:string;content:string;kind:string;status:string;created_at:string};
export default async function Page(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login');const entries=await soft<Entry[]>(supabase.from('aq_quick_inbox').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(80),[]);return <main className="min-h-screen px-4 pb-28 pt-6"><div className="mx-auto max-w-md"><h1 className="text-2xl font-black">Caixa de entrada rápida</h1><p className="mt-1 text-sm text-slate-400">Jogue ideias soltas aqui e organize depois.</p><ActionForm action={saveQuickInbox} resetOnSuccess className="mt-5 rounded-3xl border border-slate-800 bg-slate-900 p-4"><textarea name="content" required className="h-28 w-full rounded-xl border border-slate-700 bg-slate-950 p-3" placeholder="Ex.: pagar boleto, ideia de treino, gasto, lembrete..."/><select name="kind" className="mt-3 w-full rounded-xl border border-slate-700 bg-slate-950 p-3"><option value="idea">Ideia</option><option value="task">Tarefa</option><option value="finance">Financeiro</option><option value="workout">Treino</option><option value="fasting">Jejum</option></select><button className="mt-3 w-full rounded-xl bg-violet-600 p-3 font-bold">Capturar</button></ActionForm><section className="mt-5 space-y-2">{entries.map(e=><article key={e.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-3"><div className="flex items-start justify-between gap-3"><div><p className="whitespace-pre-wrap text-sm font-semibold">{e.content}</p><p className="mt-1 text-xs text-slate-400">{e.kind} · {e.status}</p></div></div>{e.status==='open'&&<div className="mt-3 grid grid-cols-2 gap-2"><ActionForm action={updateQuickInboxForm}><input type="hidden" name="id" value={e.id}/><input type="hidden" name="status" value="converted"/><button className="w-full rounded-xl border border-emerald-700 p-2 text-xs text-emerald-200">Marcar organizado</button></ActionForm><ActionForm action={updateQuickInboxForm}><input type="hidden" name="id" value={e.id}/><input type="hidden" name="status" value="archived"/><button className="w-full rounded-xl border border-slate-700 p-2 text-xs text-slate-300">Arquivar</button></ActionForm></div>}</article>)}{!entries.length&&<p className="rounded-2xl border border-slate-800 p-4 text-sm text-slate-400">Nada capturado ainda.</p>}</section></div></main>}
